<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use FortisAPILib\Controllers\TerminalsController;
use FortisAPILib\Exceptions;

class TerminalsControllerTest extends BaseTestController
{
    /**
     * @var TerminalsController TerminalsController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getTerminalsController();
    }

    public function testListAllTerminalsRelated()
    {
        // Parameters for the API call
        $page = null;
        $order = null;
        $filterBy = null;
        $expand = null;
        $format = null;
        $typeahead = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listAllTerminalsRelated(
                $page,
                $order,
                $filterBy,
                $expand,
                $format,
                $typeahead,
                $fields
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"TerminalsCollection","list":[{"location_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","default_product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","terminal_applica' .
                'tion_id":"11e95f8ec39de8fbdb0a4f1a","terminal_cvm_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","terminal_manufacturer_code":"1","title":"My terminal","mac_address":"3D:F2:C' .
                '9:A6:B3:4F","local_ip_address":"192.168.0.10","port":10009,"serial_number":"123' .
                '4567890","terminal_number":"973456789012367","terminal_timeouts":{"card_entry_t' .
                'imeout":47,"device_terms_prompt_timeout":30,"overall_timeout":125,"pin_entry_ti' .
                'meout":40,"signature_input_timeout":35,"signature_submit_timeout":38,"status_di' .
                'splay_time":12,"tip_cashback_timeout":25,"transaction_timeout":17},"tip_percent' .
                's":{"percent_1":0,"percent_2":2,"percent_3":99},"header_line_1":"line 1 sample"' .
                ',"header_line_2":"line 2 sample","header_line_3":"line 3 sample","header_line_4' .
                '":"line 4 sample","header_line_5":"line 5 sample","trailer_line_1":"trailer 1 s' .
                'ample","trailer_line_2":"trailer 2 sample","trailer_line_3":"trailer 3 sample",' .
                '"trailer_line_4":"trailer 4 sample","trailer_line_5":"trailer 5 sample","defaul' .
                't_checkin":"2021-12-01","default_checkout":"2021-12-01","default_room_rate":56,' .
                '"default_room_number":"303","debit":false,"emv":false,"cashback_enable":false,"' .
                'print_enable":false,"sig_capture_enable":false,"is_provisioned":false,"tip_enab' .
                'le":false,"validated_decryption":false,"communication_type":"http","active":tru' .
                'e,"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040' .
                '992,"last_registration_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","location":{"id":"11e95f8ec39' .
                'de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"account_number' .
                '":"5454545454545454","address":{"city":"Novi","state":"MI","postal_code":"48375' .
                '","country":"US"},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1a","contact_emai' .
                'l_trx_receipt_default":true,"default_ach":"11e608a7d515f1e093242bb2","default_c' .
                'c":"11e608a442a5f1e092242dda","email_reply_to":"email@domain.com","fax":"333999' .
                '8822","location_api_id":"location-111111","location_api_key":"AE34BBCAADF4AE34B' .
                'BCAADF4","location_c1":"custom 1","location_c2":"custom 2","location_c3":"custo' .
                'm data 3","name":"Sample Company Headquarters","office_phone":"2481234567","off' .
                'ice_ext_phone":"1021021209","tz":"America/New_York","parent_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","show_contact_notes":true,"show_contact_files":true,"created_user_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","location_type":"merchant","ticket_hash_key":"A5F' .
                '443CADF4AE34BBCAADF4"},"created_user":{"account_number":"5454545454545454","bra' .
                'nding_domain_url":"{branding_domain_url}","cell_phone":"3339998822","company_na' .
                'me":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date' .
                '_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@d' .
                'omain.com","email_trx_receipt":true,"home_phone":"3339998822","first_name":"Joh' .
                'n","last_name":"Smith","locale":"en-US","office_phone":"3339998822","office_ext' .
                '_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_pass' .
                'word":null,"terms_condition_code":"20220308","tz":"America/New_York","ui_prefs"' .
                ':{"entry_page":"dashboard","page_size":2,"report_export_type":"csv","process_me' .
                'thod":"virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"userna' .
                'me":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"u' .
                'ser_type_code":100,"password":null,"zip":"48375","location_id":"11e95f8ec39de8f' .
                'bdb0a4f1a","status_code":1,"api_only":false,"is_invitation":false,"address":{"c' .
                'ity":"Novi","state":"MI","postal_code":"48375","country":"US"},"id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","status":true,"login_attempts":0,"last_login_ts":1422040992,"cr' .
                'eated_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","cur' .
                'rent_date_time":"2019-03-11T10:38:26-0700","current_login":1422040992,"log_api_' .
                'response_body_ts":1422040992},"terminal_application":{"standalone":true,"emv_ca' .
                'pable":true,"nfc_capable":false,"pin_capable":true,"print_capable":false,"msr_c' .
                'apable":true,"sig_capture_capable":false,"mpos_terminal":false,"title":"Ingenic' .
                'o Link2500","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_t' .
                's":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"changelogs":[{"id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","model":"' .
                'TransactionRequest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","changelo' .
                'g_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"1643616000"' .
                '}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com","first' .
                '_name":"Bob","last_name":"Fairview"}}],"terminal_routers":[{"mac_address":"3D:F' .
                '2:C9:A6:B3:4F","location_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbd' .
                'b0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11' .
                'e95f8ec39de8fbdb0a4f1a"}],"has_terminal_routers":true,"terminal_cvm":{"terminal' .
                '_manufacturer_code":4,"title":"CVM One","contact_data":null,"contactless_data":' .
                'null,"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422' .
                '040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8' .
                'ec39de8fbdb0a4f1a"},"terminal_manufacturer":{"title":"My terminal","idtype":"ma' .
                'c","code":"4","created_ts":1422040992,"modified_ts":1422040992,"created_user_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}}],"' .
                'links":{"type":"Links","first":"/v1/endpoint?page[size]=10&page[number]=1","pre' .
                'vious":"/v1/endpoint?page[size]=10&page[number]=5","next":"/v1/endpoint?page[si' .
                'ze]=10&page[number]=7","last":"/v1/endpoint?page[size]=10&page[number]=42"},"pa' .
                'gination":{"type":"Pagination","total_count":423,"page_count":42,"page_number":' .
                '6,"page_size":10},"sort":{"type":"Sorting","fields":[{"field":"last_name","orde' .
                'r":"asc"}]}}'
            )))
            ->assert();
    }

    public function testViewSingleTerminalsRecord()
    {
        // Parameters for the API call
        $terminalId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->viewSingleTerminalsRecord($terminalId, $expand, $fields);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Terminal","data":{"location_id":"11e95f8ec39de8fbdb0a4f1a","default_p' .
                'roduct_transaction_id":"11e95f8ec39de8fbdb0a4f1a","terminal_application_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","terminal_cvm_id":"11e95f8ec39de8fbdb0a4f1a","terminal_' .
                'manufacturer_code":"1","title":"My terminal","mac_address":"3D:F2:C9:A6:B3:4F",' .
                '"local_ip_address":"192.168.0.10","port":10009,"serial_number":"1234567890","te' .
                'rminal_number":"973456789012367","terminal_timeouts":{"card_entry_timeout":47,"' .
                'device_terms_prompt_timeout":30,"overall_timeout":125,"pin_entry_timeout":40,"s' .
                'ignature_input_timeout":35,"signature_submit_timeout":38,"status_display_time":' .
                '12,"tip_cashback_timeout":25,"transaction_timeout":17},"tip_percents":{"percent' .
                '_1":0,"percent_2":2,"percent_3":99},"header_line_1":"line 1 sample","header_lin' .
                'e_2":"line 2 sample","header_line_3":"line 3 sample","header_line_4":"line 4 sa' .
                'mple","header_line_5":"line 5 sample","trailer_line_1":"trailer 1 sample","trai' .
                'ler_line_2":"trailer 2 sample","trailer_line_3":"trailer 3 sample","trailer_lin' .
                'e_4":"trailer 4 sample","trailer_line_5":"trailer 5 sample","default_checkin":"' .
                '2021-12-01","default_checkout":"2021-12-01","default_room_rate":56,"default_roo' .
                'm_number":"303","debit":false,"emv":false,"cashback_enable":false,"print_enable' .
                '":false,"sig_capture_enable":false,"is_provisioned":false,"tip_enable":false,"v' .
                'alidated_decryption":false,"communication_type":"http","active":true,"id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"last_re' .
                'gistration_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modifie' .
                'd_user_id":"11e95f8ec39de8fbdb0a4f1a","location":{"id":"11e95f8ec39de8fbdb0a4f1' .
                'a","created_ts":1422040992,"modified_ts":1422040992,"account_number":"545454545' .
                '4545454","address":{"city":"Novi","state":"MI","postal_code":"48375","country":' .
                '"US"},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receip' .
                't_default":true,"default_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a4' .
                '42a5f1e092242dda","email_reply_to":"email@domain.com","fax":"3339998822","locat' .
                'ion_api_id":"location-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","lo' .
                'cation_c1":"custom 1","location_c2":"custom 2","location_c3":"custom data 3","n' .
                'ame":"Sample Company Headquarters","office_phone":"2481234567","office_ext_phon' .
                'e":"1021021209","tz":"America/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"show_contact_notes":true,"show_contact_files":true,"created_user_id":"11e95f8e' .
                'c39de8fbdb0a4f1a","location_type":"merchant","ticket_hash_key":"A5F443CADF4AE34' .
                'BBCAADF4"},"created_user":{"account_number":"5454545454545454","branding_domain' .
                '_url":"{branding_domain_url}","cell_phone":"3339998822","company_name":"Fortis ' .
                'Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"' .
                '2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","' .
                'email_trx_receipt":true,"home_phone":"3339998822","first_name":"John","last_nam' .
                'e":"Smith","locale":"en-US","office_phone":"3339998822","office_ext_phone":"5",' .
                '"primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"' .
                'terms_condition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_pag' .
                'e":"dashboard","page_size":2,"report_export_type":"csv","process_method":"virtu' .
                'al_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_n' .
                'ame}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_cod' .
                'e":100,"password":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'status_code":1,"api_only":false,"is_invitation":false,"address":{"city":"Novi",' .
                '"state":"MI","postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f' .
                '1a","status":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":14' .
                '22040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"terms_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_ti' .
                'me":"2019-03-11T10:38:26-0700","current_login":1422040992,"log_api_response_bod' .
                'y_ts":1422040992},"terminal_application":{"standalone":true,"emv_capable":true,' .
                '"nfc_capable":false,"pin_capable":true,"print_capable":false,"msr_capable":true' .
                ',"sig_capture_capable":false,"mpos_terminal":false,"title":"Ingenico Link2500",' .
                '"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204099' .
                '2,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"changelogs":[{"id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","model":"TransactionR' .
                'equest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"1643616000"}],"user":{"' .
                'id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com","first_name":"Bob"' .
                ',"last_name":"Fairview"}}],"terminal_routers":[{"mac_address":"3D:F2:C9:A6:B3:4' .
                'F","location_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","cr' .
                'eated_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8' .
                'fbdb0a4f1a"}],"has_terminal_routers":true,"terminal_cvm":{"terminal_manufacture' .
                'r_code":4,"title":"CVM One","contact_data":null,"contactless_data":null,"id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"crea' .
                'ted_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0' .
                'a4f1a"},"terminal_manufacturer":{"title":"My terminal","idtype":"mac","code":"4' .
                '","created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}}}'
            )))
            ->assert();
    }
}
