<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Authentication;

/**
 * Interface for defining the behavior of Authentication.
 */
interface AccessTokenCredentials
{
    /**
     * String value for accessToken.
     */
    public function getAccessToken(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $accessToken Access Token
     */
    public function equals(string $accessToken): bool;
}
