<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Authentication;

/**
 * Interface for defining the behavior of Authentication.
 */
interface DeveloperIdCredentials
{
    /**
     * String value for developerId.
     */
    public function getDeveloperId(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $developerId Developer ID
     */
    public function equals(string $developerId): bool;
}
