<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Authentication;

/**
 * Interface for defining the behavior of Authentication.
 */
interface UserIdCredentials
{
    /**
     * String value for userId.
     */
    public function getUserId(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $userId User ID
     */
    public function equals(string $userId): bool;
}
