<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Authentication;

/**
 * Interface for defining the behavior of Authentication.
 */
interface UserApiKeyCredentials
{
    /**
     * String value for userApiKey.
     */
    public function getUserApiKey(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $userApiKey User API Key
     */
    public function equals(string $userApiKey): bool;
}
