<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Authentication;

use Core\Utils\CoreHelper;

/**
 * Utility class for initializing UserId security credentials.
 */
class UserIdCredentialsBuilder
{
    /**
     * @var array
     */
    private $config;

    private function __construct(array $config)
    {
        $this->config = $config;
    }

    /**
     * Initializer for UserIdCredentialsBuilder
     *
     * @param string $userId
     */
    public static function init(string $userId): self
    {
        return new self(['userId' => $userId]);
    }

    /**
     * Setter for UserId.
     *
     * @param string $userId
     *
     * @return $this
     */
    public function userId(string $userId): self
    {
        $this->config['userId'] = $userId;
        return $this;
    }

    public function getConfiguration(): array
    {
        return CoreHelper::clone($this->config);
    }
}
