<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\BankAccount1;

/**
 * Builder for model BankAccount1
 *
 * @see BankAccount1
 */
class BankAccount1Builder
{
    /**
     * @var BankAccount1
     */
    private $instance;

    private function __construct(BankAccount1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new bank account 1 Builder object.
     */
    public static function init(
        string $accountHolderName,
        string $routingNumber,
        string $accountNumber,
        string $accountType
    ): self {
        return new self(new BankAccount1($accountHolderName, $routingNumber, $accountNumber, $accountType));
    }

    /**
     * Sets is primary field.
     */
    public function isPrimary(?bool $value): self
    {
        $this->instance->setIsPrimary($value);
        return $this;
    }

    /**
     * Sets alt deposit types field.
     */
    public function altDepositTypes(?array $value): self
    {
        $this->instance->setAltDepositTypes($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new bank account 1 object.
     */
    public function build(): BankAccount1
    {
        return CoreHelper::clone($this->instance);
    }
}
