<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Data5;

/**
 * Builder for model Data5
 *
 * @see Data5
 */
class Data5Builder
{
    /**
     * @var Data5
     */
    private $instance;

    private function __construct(Data5 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new data 5 Builder object.
     */
    public static function init(): self
    {
        return new self(new Data5());
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets email log id field.
     */
    public function emailLogId(?string $value): self
    {
        $this->instance->setEmailLogId($value);
        return $this;
    }

    /**
     * Sets success field.
     */
    public function success(?bool $value): self
    {
        $this->instance->setSuccess($value);
        return $this;
    }

    /**
     * Sets email field.
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new data 5 object.
     */
    public function build(): Data5
    {
        return CoreHelper::clone($this->instance);
    }
}
