<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Data28;

/**
 * Builder for model Data28
 *
 * @see Data28
 */
class Data28Builder
{
    /**
     * @var Data28
     */
    private $instance;

    private function __construct(Data28 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new data 28 Builder object.
     */
    public static function init(): self
    {
        return new self(new Data28());
    }

    /**
     * Sets user api key field.
     */
    public function userApiKey(?string $value): self
    {
        $this->instance->setUserApiKey($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new data 28 object.
     */
    public function build(): Data28
    {
        return CoreHelper::clone($this->instance);
    }
}
