<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Address1;
use FortisAPILib\Models\BrandingDomain;
use FortisAPILib\Models\CreatedUser;
use FortisAPILib\Models\Data10;
use FortisAPILib\Models\DeveloperCompany;
use FortisAPILib\Models\Parent3;
use FortisAPILib\Models\ProductInvoice;
use FortisAPILib\Models\QuickInvoiceSetting;

/**
 * Builder for model Data10
 *
 * @see Data10
 */
class Data10Builder
{
    /**
     * @var Data10
     */
    private $instance;

    private function __construct(Data10 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new data 10 Builder object.
     */
    public static function init(): self
    {
        return new self(new Data10());
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets created ts field.
     */
    public function createdTs(?int $value): self
    {
        $this->instance->setCreatedTs($value);
        return $this;
    }

    /**
     * Sets modified ts field.
     */
    public function modifiedTs(?int $value): self
    {
        $this->instance->setModifiedTs($value);
        return $this;
    }

    /**
     * Sets account number field.
     */
    public function accountNumber(?string $value): self
    {
        $this->instance->setAccountNumber($value);
        return $this;
    }

    /**
     * Unsets account number field.
     */
    public function unsetAccountNumber(): self
    {
        $this->instance->unsetAccountNumber();
        return $this;
    }

    /**
     * Sets address field.
     */
    public function address(?Address1 $value): self
    {
        $this->instance->setAddress($value);
        return $this;
    }

    /**
     * Sets branding domain id field.
     */
    public function brandingDomainId(?string $value): self
    {
        $this->instance->setBrandingDomainId($value);
        return $this;
    }

    /**
     * Unsets branding domain id field.
     */
    public function unsetBrandingDomainId(): self
    {
        $this->instance->unsetBrandingDomainId();
        return $this;
    }

    /**
     * Sets contact email trx receipt default field.
     */
    public function contactEmailTrxReceiptDefault(?bool $value): self
    {
        $this->instance->setContactEmailTrxReceiptDefault($value);
        return $this;
    }

    /**
     * Sets default ach field.
     */
    public function defaultAch(?string $value): self
    {
        $this->instance->setDefaultAch($value);
        return $this;
    }

    /**
     * Unsets default ach field.
     */
    public function unsetDefaultAch(): self
    {
        $this->instance->unsetDefaultAch();
        return $this;
    }

    /**
     * Sets default cc field.
     */
    public function defaultCc(?string $value): self
    {
        $this->instance->setDefaultCc($value);
        return $this;
    }

    /**
     * Unsets default cc field.
     */
    public function unsetDefaultCc(): self
    {
        $this->instance->unsetDefaultCc();
        return $this;
    }

    /**
     * Sets email reply to field.
     */
    public function emailReplyTo(?string $value): self
    {
        $this->instance->setEmailReplyTo($value);
        return $this;
    }

    /**
     * Unsets email reply to field.
     */
    public function unsetEmailReplyTo(): self
    {
        $this->instance->unsetEmailReplyTo();
        return $this;
    }

    /**
     * Sets fax field.
     */
    public function fax(?string $value): self
    {
        $this->instance->setFax($value);
        return $this;
    }

    /**
     * Unsets fax field.
     */
    public function unsetFax(): self
    {
        $this->instance->unsetFax();
        return $this;
    }

    /**
     * Sets location api id field.
     */
    public function locationApiId(?string $value): self
    {
        $this->instance->setLocationApiId($value);
        return $this;
    }

    /**
     * Unsets location api id field.
     */
    public function unsetLocationApiId(): self
    {
        $this->instance->unsetLocationApiId();
        return $this;
    }

    /**
     * Sets location api key field.
     */
    public function locationApiKey(?string $value): self
    {
        $this->instance->setLocationApiKey($value);
        return $this;
    }

    /**
     * Unsets location api key field.
     */
    public function unsetLocationApiKey(): self
    {
        $this->instance->unsetLocationApiKey();
        return $this;
    }

    /**
     * Sets location c 1 field.
     */
    public function locationC1(?string $value): self
    {
        $this->instance->setLocationC1($value);
        return $this;
    }

    /**
     * Unsets location c 1 field.
     */
    public function unsetLocationC1(): self
    {
        $this->instance->unsetLocationC1();
        return $this;
    }

    /**
     * Sets location c 2 field.
     */
    public function locationC2(?string $value): self
    {
        $this->instance->setLocationC2($value);
        return $this;
    }

    /**
     * Unsets location c 2 field.
     */
    public function unsetLocationC2(): self
    {
        $this->instance->unsetLocationC2();
        return $this;
    }

    /**
     * Sets location c 3 field.
     */
    public function locationC3(?string $value): self
    {
        $this->instance->setLocationC3($value);
        return $this;
    }

    /**
     * Unsets location c 3 field.
     */
    public function unsetLocationC3(): self
    {
        $this->instance->unsetLocationC3();
        return $this;
    }

    /**
     * Sets name field.
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets office phone field.
     */
    public function officePhone(?string $value): self
    {
        $this->instance->setOfficePhone($value);
        return $this;
    }

    /**
     * Unsets office phone field.
     */
    public function unsetOfficePhone(): self
    {
        $this->instance->unsetOfficePhone();
        return $this;
    }

    /**
     * Sets office ext phone field.
     */
    public function officeExtPhone(?string $value): self
    {
        $this->instance->setOfficeExtPhone($value);
        return $this;
    }

    /**
     * Unsets office ext phone field.
     */
    public function unsetOfficeExtPhone(): self
    {
        $this->instance->unsetOfficeExtPhone();
        return $this;
    }

    /**
     * Sets tz field.
     */
    public function tz(?string $value): self
    {
        $this->instance->setTz($value);
        return $this;
    }

    /**
     * Unsets tz field.
     */
    public function unsetTz(): self
    {
        $this->instance->unsetTz();
        return $this;
    }

    /**
     * Sets parent id field.
     */
    public function parentId(?string $value): self
    {
        $this->instance->setParentId($value);
        return $this;
    }

    /**
     * Sets show contact notes field.
     */
    public function showContactNotes(?bool $value): self
    {
        $this->instance->setShowContactNotes($value);
        return $this;
    }

    /**
     * Sets show contact files field.
     */
    public function showContactFiles(?bool $value): self
    {
        $this->instance->setShowContactFiles($value);
        return $this;
    }

    /**
     * Sets created user id field.
     */
    public function createdUserId(?string $value): self
    {
        $this->instance->setCreatedUserId($value);
        return $this;
    }

    /**
     * Unsets created user id field.
     */
    public function unsetCreatedUserId(): self
    {
        $this->instance->unsetCreatedUserId();
        return $this;
    }

    /**
     * Sets location type field.
     */
    public function locationType(?string $value): self
    {
        $this->instance->setLocationType($value);
        return $this;
    }

    /**
     * Unsets location type field.
     */
    public function unsetLocationType(): self
    {
        $this->instance->unsetLocationType();
        return $this;
    }

    /**
     * Sets ticket hash key field.
     */
    public function ticketHashKey(?string $value): self
    {
        $this->instance->setTicketHashKey($value);
        return $this;
    }

    /**
     * Unsets ticket hash key field.
     */
    public function unsetTicketHashKey(): self
    {
        $this->instance->unsetTicketHashKey();
        return $this;
    }

    /**
     * Sets parent field.
     */
    public function parent(?Parent3 $value): self
    {
        $this->instance->setParent($value);
        return $this;
    }

    /**
     * Sets users field.
     */
    public function users(?array $value): self
    {
        $this->instance->setUsers($value);
        return $this;
    }

    /**
     * Sets is deletable field.
     */
    public function isDeletable(?bool $value): self
    {
        $this->instance->setIsDeletable($value);
        return $this;
    }

    /**
     * Sets terminals field.
     */
    public function terminals(?array $value): self
    {
        $this->instance->setTerminals($value);
        return $this;
    }

    /**
     * Sets branding domain field.
     */
    public function brandingDomain(?BrandingDomain $value): self
    {
        $this->instance->setBrandingDomain($value);
        return $this;
    }

    /**
     * Sets product invoice field.
     */
    public function productInvoice(?ProductInvoice $value): self
    {
        $this->instance->setProductInvoice($value);
        return $this;
    }

    /**
     * Sets product files field.
     */
    public function productFiles(?array $value): self
    {
        $this->instance->setProductFiles($value);
        return $this;
    }

    /**
     * Sets created user field.
     */
    public function createdUser(?CreatedUser $value): self
    {
        $this->instance->setCreatedUser($value);
        return $this;
    }

    /**
     * Sets changelogs field.
     */
    public function changelogs(?array $value): self
    {
        $this->instance->setChangelogs($value);
        return $this;
    }

    /**
     * Sets product transactions field.
     */
    public function productTransactions(?array $value): self
    {
        $this->instance->setProductTransactions($value);
        return $this;
    }

    /**
     * Sets terminal routers field.
     */
    public function terminalRouters(?array $value): self
    {
        $this->instance->setTerminalRouters($value);
        return $this;
    }

    /**
     * Sets developer company field.
     */
    public function developerCompany(?DeveloperCompany $value): self
    {
        $this->instance->setDeveloperCompany($value);
        return $this;
    }

    /**
     * Sets developer company id field.
     */
    public function developerCompanyId(?string $value): self
    {
        $this->instance->setDeveloperCompanyId($value);
        return $this;
    }

    /**
     * Unsets developer company id field.
     */
    public function unsetDeveloperCompanyId(): self
    {
        $this->instance->unsetDeveloperCompanyId();
        return $this;
    }

    /**
     * Sets helppages field.
     */
    public function helppages(?array $value): self
    {
        $this->instance->setHelppages($value);
        return $this;
    }

    /**
     * Sets quick invoice setting field.
     */
    public function quickInvoiceSetting(?QuickInvoiceSetting $value): self
    {
        $this->instance->setQuickInvoiceSetting($value);
        return $this;
    }

    /**
     * Sets location billing accounts field.
     */
    public function locationBillingAccounts(?array $value): self
    {
        $this->instance->setLocationBillingAccounts($value);
        return $this;
    }

    /**
     * Sets marketplaces field.
     */
    public function marketplaces(?array $value): self
    {
        $this->instance->setMarketplaces($value);
        return $this;
    }

    /**
     * Sets locationmarketplaces field.
     */
    public function locationmarketplaces(?array $value): self
    {
        $this->instance->setLocationmarketplaces($value);
        return $this;
    }

    /**
     * Sets addons field.
     */
    public function addons(?array $value): self
    {
        $this->instance->setAddons($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new data 10 object.
     */
    public function build(): Data10
    {
        return CoreHelper::clone($this->instance);
    }
}
