<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Data15;

/**
 * Builder for model Data15
 *
 * @see Data15
 */
class Data15Builder
{
    /**
     * @var Data15
     */
    private $instance;

    private function __construct(Data15 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new data 15 Builder object.
     */
    public static function init(): self
    {
        return new self(new Data15());
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets email log id field.
     */
    public function emailLogId(?string $value): self
    {
        $this->instance->setEmailLogId($value);
        return $this;
    }

    /**
     * Unsets email log id field.
     */
    public function unsetEmailLogId(): self
    {
        $this->instance->unsetEmailLogId();
        return $this;
    }

    /**
     * Sets sms log id field.
     */
    public function smsLogId(?string $value): self
    {
        $this->instance->setSmsLogId($value);
        return $this;
    }

    /**
     * Unsets sms log id field.
     */
    public function unsetSmsLogId(): self
    {
        $this->instance->unsetSmsLogId();
        return $this;
    }

    /**
     * Sets success field.
     */
    public function success(?bool $value): self
    {
        $this->instance->setSuccess($value);
        return $this;
    }

    /**
     * Sets sms success field.
     */
    public function smsSuccess(?bool $value): self
    {
        $this->instance->setSmsSuccess($value);
        return $this;
    }

    /**
     * Sets email field.
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Unsets email field.
     */
    public function unsetEmail(): self
    {
        $this->instance->unsetEmail();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new data 15 object.
     */
    public function build(): Data15
    {
        return CoreHelper::clone($this->instance);
    }
}
