<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\FilterBy;

/**
 * Builder for model FilterBy
 *
 * @see FilterBy
 */
class FilterByBuilder
{
    /**
     * @var FilterBy
     */
    private $instance;

    private function __construct(FilterBy $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new filter by Builder object.
     */
    public static function init(string $key, string $operator, $value): self
    {
        return new self(new FilterBy($key, $operator, $value));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new filter by object.
     */
    public function build(): FilterBy
    {
        return CoreHelper::clone($this->instance);
    }
}
