<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Footer;
use FortisAPILib\Models\Settings;

/**
 * Builder for model Footer
 *
 * @see Footer
 */
class FooterBuilder
{
    /**
     * @var Footer
     */
    private $instance;

    private function __construct(Footer $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new footer Builder object.
     */
    public static function init(): self
    {
        return new self(new Footer());
    }

    /**
     * Sets settings field.
     */
    public function settings(?Settings $value): self
    {
        $this->instance->setSettings($value);
        return $this;
    }

    /**
     * Sets fields field.
     */
    public function fields(?array $value): self
    {
        $this->instance->setFields($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new footer object.
     */
    public function build(): Footer
    {
        return CoreHelper::clone($this->instance);
    }
}
