<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\ItemList4;

/**
 * Builder for model ItemList4
 *
 * @see ItemList4
 */
class ItemList4Builder
{
    /**
     * @var ItemList4
     */
    private $instance;

    private function __construct(ItemList4 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new item list 4 Builder object.
     */
    public static function init(string $name, int $amount): self
    {
        return new self(new ItemList4($name, $amount));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new item list 4 object.
     */
    public function build(): ItemList4
    {
        return CoreHelper::clone($this->instance);
    }
}
