<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\KycResponseObject;

/**
 * Builder for model KycResponseObject
 *
 * @see KycResponseObject
 */
class KycResponseObjectBuilder
{
    /**
     * @var KycResponseObject
     */
    private $instance;

    private function __construct(KycResponseObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new kyc response object Builder object.
     */
    public static function init(string $value, string $type): self
    {
        return new self(new KycResponseObject($value, $type));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new kyc response object object.
     */
    public function build(): KycResponseObject
    {
        return CoreHelper::clone($this->instance);
    }
}
