<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Method40;

/**
 * Builder for model Method40
 *
 * @see Method40
 */
class Method40Builder
{
    /**
     * @var Method40
     */
    private $instance;

    private function __construct(Method40 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new method 40 Builder object.
     */
    public static function init(string $type, string $productTransactionId): self
    {
        return new self(new Method40($type, $productTransactionId));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new method 40 object.
     */
    public function build(): Method40
    {
        return CoreHelper::clone($this->instance);
    }
}
