<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Order19;

/**
 * Builder for model Order19
 *
 * @see Order19
 */
class Order19Builder
{
    /**
     * @var Order19
     */
    private $instance;

    private function __construct(Order19 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new order 19 Builder object.
     */
    public static function init(string $key, string $operator): self
    {
        return new self(new Order19($key, $operator));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new order 19 object.
     */
    public function build(): Order19
    {
        return CoreHelper::clone($this->instance);
    }
}
