<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\QuickInvoiceSetting;

/**
 * Builder for model QuickInvoiceSetting
 *
 * @see QuickInvoiceSetting
 */
class QuickInvoiceSettingBuilder
{
    /**
     * @var QuickInvoiceSetting
     */
    private $instance;

    private function __construct(QuickInvoiceSetting $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new quick invoice setting Builder object.
     */
    public static function init(): self
    {
        return new self(new QuickInvoiceSetting());
    }

    /**
     * Sets location api id field.
     */
    public function locationApiId(?string $value): self
    {
        $this->instance->setLocationApiId($value);
        return $this;
    }

    /**
     * Unsets location api id field.
     */
    public function unsetLocationApiId(): self
    {
        $this->instance->unsetLocationApiId();
        return $this;
    }

    /**
     * Sets location id field.
     */
    public function locationId(?string $value): self
    {
        $this->instance->setLocationId($value);
        return $this;
    }

    /**
     * Sets quick invoice template field.
     */
    public function quickInvoiceTemplate(?string $value): self
    {
        $this->instance->setQuickInvoiceTemplate($value);
        return $this;
    }

    /**
     * Sets default allow partial pay field.
     */
    public function defaultAllowPartialPay(?bool $value): self
    {
        $this->instance->setDefaultAllowPartialPay($value);
        return $this;
    }

    /**
     * Sets default notification on due date field.
     */
    public function defaultNotificationOnDueDate(?bool $value): self
    {
        $this->instance->setDefaultNotificationOnDueDate($value);
        return $this;
    }

    /**
     * Sets default notification days after due date field.
     */
    public function defaultNotificationDaysAfterDueDate(?float $value): self
    {
        $this->instance->setDefaultNotificationDaysAfterDueDate($value);
        return $this;
    }

    /**
     * Sets default notification days before due date field.
     */
    public function defaultNotificationDaysBeforeDueDate(?float $value): self
    {
        $this->instance->setDefaultNotificationDaysBeforeDueDate($value);
        return $this;
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new quick invoice setting object.
     */
    public function build(): QuickInvoiceSetting
    {
        return CoreHelper::clone($this->instance);
    }
}
