<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Data16;
use FortisAPILib\Models\ResponseRecurring;

/**
 * Builder for model ResponseRecurring
 *
 * @see ResponseRecurring
 */
class ResponseRecurringBuilder
{
    /**
     * @var ResponseRecurring
     */
    private $instance;

    private function __construct(ResponseRecurring $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new response recurring Builder object.
     */
    public static function init(): self
    {
        return new self(new ResponseRecurring());
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets data field.
     */
    public function data(?Data16 $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new response recurring object.
     */
    public function build(): ResponseRecurring
    {
        return CoreHelper::clone($this->instance);
    }
}
