<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Signature;

/**
 * Builder for model Signature
 *
 * @see Signature
 */
class SignatureBuilder
{
    /**
     * @var Signature
     */
    private $instance;

    private function __construct(Signature $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new signature Builder object.
     */
    public static function init(): self
    {
        return new self(new Signature());
    }

    /**
     * Sets signature field.
     */
    public function signature(?string $value): self
    {
        $this->instance->setSignature($value);
        return $this;
    }

    /**
     * Sets resource field.
     */
    public function resource(?string $value): self
    {
        $this->instance->setResource($value);
        return $this;
    }

    /**
     * Sets resource id field.
     */
    public function resourceId(?string $value): self
    {
        $this->instance->setResourceId($value);
        return $this;
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets created ts field.
     */
    public function createdTs(?int $value): self
    {
        $this->instance->setCreatedTs($value);
        return $this;
    }

    /**
     * Sets modified ts field.
     */
    public function modifiedTs(?int $value): self
    {
        $this->instance->setModifiedTs($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new signature object.
     */
    public function build(): Signature
    {
        return CoreHelper::clone($this->instance);
    }
}
