<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Status5;

/**
 * Builder for model Status5
 *
 * @see Status5
 */
class Status5Builder
{
    /**
     * @var Status5
     */
    private $instance;

    private function __construct(Status5 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new status 5 Builder object.
     */
    public static function init(): self
    {
        return new self(new Status5());
    }

    /**
     * Sets response code field.
     */
    public function responseCode(?string $value): self
    {
        $this->instance->setResponseCode($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new status 5 object.
     */
    public function build(): Status5
    {
        return CoreHelper::clone($this->instance);
    }
}
