<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models;

use stdClass;

/**
 * Array of merchant owners.
 */
class Owner implements \JsonSerializable
{
    /**
     * @var string
     */
    private $firstName;

    /**
     * @var string
     */
    private $lastName;

    /**
     * @var array
     */
    private $middleName = [];

    /**
     * @var string
     */
    private $title;

    /**
     * @var string
     */
    private $dateOfBirth;

    /**
     * @var string
     */
    private $addressLine1;

    /**
     * @var string
     */
    private $addressLine2;

    /**
     * @var string
     */
    private $city;

    /**
     * @var string
     */
    private $stateProvince;

    /**
     * @var string
     */
    private $postalCode;

    /**
     * @var string
     */
    private $countryCode;

    /**
     * @var string
     */
    private $ssn;

    /**
     * @var int
     */
    private $ownershipPercent;

    /**
     * @var string
     */
    private $phoneNumber;

    /**
     * @var string
     */
    private $emailAddress;

    /**
     * @var bool
     */
    private $isController;

    /**
     * @var bool
     */
    private $isSigner;

    /**
     * @param string $firstName
     * @param string $lastName
     * @param string $title
     * @param string $dateOfBirth
     * @param string $addressLine1
     * @param string $addressLine2
     * @param string $city
     * @param string $stateProvince
     * @param string $postalCode
     * @param string $countryCode
     * @param string $ssn
     * @param int $ownershipPercent
     * @param string $phoneNumber
     * @param string $emailAddress
     * @param bool $isController
     * @param bool $isSigner
     */
    public function __construct(
        string $firstName,
        string $lastName,
        string $title,
        string $dateOfBirth,
        string $addressLine1,
        string $addressLine2,
        string $city,
        string $stateProvince,
        string $postalCode,
        string $countryCode,
        string $ssn,
        int $ownershipPercent,
        string $phoneNumber,
        string $emailAddress,
        bool $isController,
        bool $isSigner
    ) {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->title = $title;
        $this->dateOfBirth = $dateOfBirth;
        $this->addressLine1 = $addressLine1;
        $this->addressLine2 = $addressLine2;
        $this->city = $city;
        $this->stateProvince = $stateProvince;
        $this->postalCode = $postalCode;
        $this->countryCode = $countryCode;
        $this->ssn = $ssn;
        $this->ownershipPercent = $ownershipPercent;
        $this->phoneNumber = $phoneNumber;
        $this->emailAddress = $emailAddress;
        $this->isController = $isController;
        $this->isSigner = $isSigner;
    }

    /**
     * Returns First Name.
     * Owner's first name.
     */
    public function getFirstName(): string
    {
        return $this->firstName;
    }

    /**
     * Sets First Name.
     * Owner's first name.
     *
     * @required
     * @maps first_name
     */
    public function setFirstName(string $firstName): void
    {
        $this->firstName = $firstName;
    }

    /**
     * Returns Last Name.
     * Owner's last name.
     */
    public function getLastName(): string
    {
        return $this->lastName;
    }

    /**
     * Sets Last Name.
     * Owner's last name.
     *
     * @required
     * @maps last_name
     */
    public function setLastName(string $lastName): void
    {
        $this->lastName = $lastName;
    }

    /**
     * Returns Middle Name.
     * Owner's middle name.
     */
    public function getMiddleName(): ?string
    {
        if (count($this->middleName) == 0) {
            return null;
        }
        return $this->middleName['value'];
    }

    /**
     * Sets Middle Name.
     * Owner's middle name.
     *
     * @maps middle_name
     */
    public function setMiddleName(?string $middleName): void
    {
        $this->middleName['value'] = $middleName;
    }

    /**
     * Unsets Middle Name.
     * Owner's middle name.
     */
    public function unsetMiddleName(): void
    {
        $this->middleName = [];
    }

    /**
     * Returns Title.
     * Owner's title.
     */
    public function getTitle(): string
    {
        return $this->title;
    }

    /**
     * Sets Title.
     * Owner's title.
     *
     * @required
     * @maps title
     */
    public function setTitle(string $title): void
    {
        $this->title = $title;
    }

    /**
     * Returns Date of Birth.
     * Owner's date of birth.
     */
    public function getDateOfBirth(): string
    {
        return $this->dateOfBirth;
    }

    /**
     * Sets Date of Birth.
     * Owner's date of birth.
     *
     * @required
     * @maps date_of_birth
     */
    public function setDateOfBirth(string $dateOfBirth): void
    {
        $this->dateOfBirth = $dateOfBirth;
    }

    /**
     * Returns Address Line 1.
     * Owner's street address.
     */
    public function getAddressLine1(): string
    {
        return $this->addressLine1;
    }

    /**
     * Sets Address Line 1.
     * Owner's street address.
     *
     * @required
     * @maps address_line_1
     */
    public function setAddressLine1(string $addressLine1): void
    {
        $this->addressLine1 = $addressLine1;
    }

    /**
     * Returns Address Line 2.
     * Line 2 of owner's address.
     */
    public function getAddressLine2(): string
    {
        return $this->addressLine2;
    }

    /**
     * Sets Address Line 2.
     * Line 2 of owner's address.
     *
     * @required
     * @maps address_line_2
     */
    public function setAddressLine2(string $addressLine2): void
    {
        $this->addressLine2 = $addressLine2;
    }

    /**
     * Returns City.
     * Owner's address city.
     */
    public function getCity(): string
    {
        return $this->city;
    }

    /**
     * Sets City.
     * Owner's address city.
     *
     * @required
     * @maps city
     */
    public function setCity(string $city): void
    {
        $this->city = $city;
    }

    /**
     * Returns State Province.
     * Owner's address state/province.
     */
    public function getStateProvince(): string
    {
        return $this->stateProvince;
    }

    /**
     * Sets State Province.
     * Owner's address state/province.
     *
     * @required
     * @maps state_province
     */
    public function setStateProvince(string $stateProvince): void
    {
        $this->stateProvince = $stateProvince;
    }

    /**
     * Returns Postal Code.
     * Owner's address postal code.
     */
    public function getPostalCode(): string
    {
        return $this->postalCode;
    }

    /**
     * Sets Postal Code.
     * Owner's address postal code.
     *
     * @required
     * @maps postal_code
     */
    public function setPostalCode(string $postalCode): void
    {
        $this->postalCode = $postalCode;
    }

    /**
     * Returns Country Code.
     * Owner's address country.
     */
    public function getCountryCode(): string
    {
        return $this->countryCode;
    }

    /**
     * Sets Country Code.
     * Owner's address country.
     *
     * @required
     * @maps country_code
     */
    public function setCountryCode(string $countryCode): void
    {
        $this->countryCode = $countryCode;
    }

    /**
     * Returns Ssn.
     * Owner's full SSN.
     */
    public function getSsn(): string
    {
        return $this->ssn;
    }

    /**
     * Sets Ssn.
     * Owner's full SSN.
     *
     * @required
     * @maps ssn
     */
    public function setSsn(string $ssn): void
    {
        $this->ssn = $ssn;
    }

    /**
     * Returns Ownership Percent.
     * Owner's ownership percent.
     */
    public function getOwnershipPercent(): int
    {
        return $this->ownershipPercent;
    }

    /**
     * Sets Ownership Percent.
     * Owner's ownership percent.
     *
     * @required
     * @maps ownership_percent
     */
    public function setOwnershipPercent(int $ownershipPercent): void
    {
        $this->ownershipPercent = $ownershipPercent;
    }

    /**
     * Returns Phone Number.
     * Owner's phone number.
     */
    public function getPhoneNumber(): string
    {
        return $this->phoneNumber;
    }

    /**
     * Sets Phone Number.
     * Owner's phone number.
     *
     * @required
     * @maps phone_number
     */
    public function setPhoneNumber(string $phoneNumber): void
    {
        $this->phoneNumber = $phoneNumber;
    }

    /**
     * Returns Email Address.
     * Owner's email address.
     */
    public function getEmailAddress(): string
    {
        return $this->emailAddress;
    }

    /**
     * Sets Email Address.
     * Owner's email address.
     *
     * @required
     * @maps email_address
     */
    public function setEmailAddress(string $emailAddress): void
    {
        $this->emailAddress = $emailAddress;
    }

    /**
     * Returns Is Controller.
     * Flag indicating whether this owner is the control owner. Maximum of 1 owner can be marked as control.
     * .
     */
    public function getIsController(): bool
    {
        return $this->isController;
    }

    /**
     * Sets Is Controller.
     * Flag indicating whether this owner is the control owner. Maximum of 1 owner can be marked as control.
     * .
     *
     * @required
     * @maps is_controller
     */
    public function setIsController(bool $isController): void
    {
        $this->isController = $isController;
    }

    /**
     * Returns Is Signer.
     * Flag indicating whether or not the owner is a signer for the business. Maximum of 1 owner can be
     * marked as signer.
     */
    public function getIsSigner(): bool
    {
        return $this->isSigner;
    }

    /**
     * Sets Is Signer.
     * Flag indicating whether or not the owner is a signer for the business. Maximum of 1 owner can be
     * marked as signer.
     *
     * @required
     * @maps is_signer
     */
    public function setIsSigner(bool $isSigner): void
    {
        $this->isSigner = $isSigner;
    }

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function addAdditionalProperty(string $name, $value)
    {
        $this->additionalProperties[$name] = $value;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['first_name']        = $this->firstName;
        $json['last_name']         = $this->lastName;
        if (!empty($this->middleName)) {
            $json['middle_name']   = $this->middleName['value'];
        }
        $json['title']             = $this->title;
        $json['date_of_birth']     = $this->dateOfBirth;
        $json['address_line_1']    = $this->addressLine1;
        $json['address_line_2']    = $this->addressLine2;
        $json['city']              = $this->city;
        $json['state_province']    = $this->stateProvince;
        $json['postal_code']       = $this->postalCode;
        $json['country_code']      = $this->countryCode;
        $json['ssn']               = $this->ssn;
        $json['ownership_percent'] = $this->ownershipPercent;
        $json['phone_number']      = $this->phoneNumber;
        $json['email_address']     = $this->emailAddress;
        $json['is_controller']     = $this->isController;
        $json['is_signer']         = $this->isSigner;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
