<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib;

use CoreInterfaces\Http\HttpConfigurations;
use FortisAPILib\Authentication\AccessTokenCredentials;
use FortisAPILib\Authentication\AccessTokenCredentialsBuilder;
use FortisAPILib\Authentication\DeveloperIdCredentials;
use FortisAPILib\Authentication\DeveloperIdCredentialsBuilder;
use FortisAPILib\Authentication\UserApiKeyCredentials;
use FortisAPILib\Authentication\UserApiKeyCredentialsBuilder;
use FortisAPILib\Authentication\UserIdCredentials;
use FortisAPILib\Authentication\UserIdCredentialsBuilder;

/**
 * An interface for all configuration parameters required by the SDK.
 */
interface ConfigurationInterface extends HttpConfigurations
{
    /**
     * Get current API environment
     */
    public function getEnvironment(): string;

    /**
     * Get the credentials to use with UserId
     */
    public function getUserIdCredentials(): UserIdCredentials;

    /**
     * Get the credentials builder instance to update credentials for UserId
     */
    public function getUserIdCredentialsBuilder(): ?UserIdCredentialsBuilder;

    /**
     * Get the credentials to use with UserApiKey
     */
    public function getUserApiKeyCredentials(): UserApiKeyCredentials;

    /**
     * Get the credentials builder instance to update credentials for UserApiKey
     */
    public function getUserApiKeyCredentialsBuilder(): ?UserApiKeyCredentialsBuilder;

    /**
     * Get the credentials to use with DeveloperId
     */
    public function getDeveloperIdCredentials(): DeveloperIdCredentials;

    /**
     * Get the credentials builder instance to update credentials for DeveloperId
     */
    public function getDeveloperIdCredentialsBuilder(): ?DeveloperIdCredentialsBuilder;

    /**
     * Get the credentials to use with AccessToken
     */
    public function getAccessTokenCredentials(): AccessTokenCredentials;

    /**
     * Get the credentials builder instance to update credentials for AccessToken
     */
    public function getAccessTokenCredentialsBuilder(): ?AccessTokenCredentialsBuilder;

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::DEFAULT_): string;
}
